# Generated by Django 5.2.4 on 2025-08-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_act_number', models.CharField(max_length=10, verbose_name='Номер АВР')),
                ('service_request_number', models.CharField(max_length=10, verbose_name='Номер заявки')),
                ('service_organization', models.CharField(max_length=100, verbose_name='Территория проведения работы')),
                ('service_work_place', models.CharField(max_length=50, verbose_name='Отметка')),
                ('service_manager_fio', models.CharField(max_length=255, verbose_name='ФИО ответсвенного за выполнение работ')),
                ('equip_garage_number', models.CharField(max_length=10, verbose_name='Гаражный номер')),
                ('equip_zavod_number', models.CharField(max_length=10, verbose_name='Заводской номер')),
                ('equip_current_narabotka', models.CharField(max_length=10, verbose_name='Текущая наработка, м/ч')),
                ('service_work_date', models.DateField(verbose_name='Дата выполнения работ')),
                ('service_time_start', models.TimeField(verbose_name='Время начала работ')),
                ('service_time_end', models.TimeField(verbose_name='Время окончания работ')),
                ('service_work_duration', models.CharField(max_length=10, verbose_name='Длительность работ')),
                ('service_reglament_work_type', models.CharField(max_length=10, verbose_name='Вид регламентного обслуживания')),
                ('service_work_description', models.TextField(verbose_name='Выполненные дополнительные работы')),
                ('service_used_materials', models.TextField(verbose_name='Использованные запасные части и материалы')),
                ('service_defect_description', models.TextField(verbose_name='Выявленные отклонения/коды ошибок')),
                ('service_recomendation', models.TextField(verbose_name='Рекомендации')),
                ('service_customer_fio', models.CharField(max_length=255, verbose_name='ФИО заказчика')),
                ('service_employer_fio', models.TextField(verbose_name='ФИО исполнителей')),
                ('service_pdf_file', models.FileField(upload_to='pdfs/', verbose_name='PDF файл акта выполненных работ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('equip_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.equipmentmodel')),
            ],
        ),
    ]
