# Generated by Django 5.2.4 on 2025-08-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=50, unique=True, verbose_name='Заводской номер')),
                ('garage_number', models.CharField(max_length=50, unique=True, verbose_name='Гаражный номер')),
                ('warranty', models.BooleanField(default=False, verbose_name='Гарантия')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='equip_garage_number',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='equip_zavod_number',
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='equip_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.equipmentmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.organization', verbose_name='Предприятяие'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='service_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.organization', verbose_name='Предприятие'),
        ),
    ]
