# Generated by Django 5.2.4 on 2025-08-04 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_equipment_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.equipmentmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='equip_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.equipmentmodel', verbose_name='Модель'),
        ),
    ]
