# Generated by Django 5.2.4 on 2025-08-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_equipment_model_alter_servicereport_equip_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Вид регламентного ТО')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.organization', verbose_name='Предприятяие'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='service_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.organization', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='service_reglament_work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.reglament', verbose_name='Вид регламентного обслуживания'),
        ),
    ]
