# Generated by Django 5.2.4 on 2025-08-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reglament_alter_equipment_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.equipment', verbose_name='Оборудование (зав.№/гар.№)'),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('tab_number', models.CharField(max_length=50, unique=True, verbose_name='Табельный №')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.organization', verbose_name='Предприятие')),
            ],
        ),
    ]
