# Generated by Django 5.2.4 on 2025-08-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_servicereport_equipment_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereport',
            name='service_employer_fio',
        ),
        migrations.AddField(
            model_name='servicereport',
            name='service_employer_fio',
            field=models.ManyToManyField(blank=True, to='reports.personal', verbose_name='Исполнители работ'),
        ),
    ]
